[ADD] connector_easypost_tracker: Create mapping for TrackingDetail and TrackingLocation
LasLabs/odoo-connector-easypost pull request #7
Opened 2016-12-12 22:50 UTC by t3ddftw

This pull request covers LABS-159 & LABS-160 as they are co-dependent (An event *must* have a location*).

[ADD] connector_easypost_tracker: Create mapping for TrackingDetail and TrackingLocation
* Create mapping importers / tests for Events
* Create mapping importers / tests for Locations
* Create Webhook controller
* Add Binders
* Update Global and tracker README
* Add Screenshots from Picking

[IMP] connector_easypost: Update test object
* Update `ObjDict` to object type with dict attributes. This allows me to use `getattr` without having uncatchable `KeyError` thrown at me.
* Fix `import_synchronizer` string lint
* Fix `import_synchronizer` `easy_import_data` by adding data object to correct object attribute
* Fix `import_synchronizer` Environment helper `_get_env_return_importer` not sending the UID over to `ConnectorSession`

2016-12-15 23:49 UTC, lasley requested changes

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/controllers/main.py
> +            ('is_default', '=', True)
Trailing comma

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/controllers/main.py
> +        '/api/easypost/webhook',
As much as I prefer this URL, you don't own this namespace. You own routes under `/connector_easypost_tracker/*`

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/models/stock_picking_tracking_event.py
> +        ('odoo_uniq', 'unique(backend_id, odoo_id)',
Isn't this enforced in `easypost.binding`?

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/models/stock_picking_tracking_event.py
> +        (eval_false('datetime'), 'date_created')
trail comma

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/models/stock_picking_tracking_group.py
> +from openerp import fields, models
It's funny how much I hated the menial task of alphabetizing imports, but now that I'm used to it I can't live without them alphabetized. It's one of those can't unsee things, right!? 😆

2016-12-15 23:49 UTC, lasley commented on connector_easypost_tracker/models/stock_picking_tracking_location.py
> +    _sql_constraints = [
I think the binding constrains this

2016-12-15 23:49 UTC, lasley commented on connector_easypost/unit/import_synchronizer.py
> +class ObjectDict(object):
Hmmmm I think maybe this needs its own file in `unit`. I feel like it's going to be lost here & it's not only related to the import (tests also use)

2016-12-16 04:17 UTC, t3ddftw commented on connector_easypost_tracker/controllers/main.py
> +        '/api/easypost/webhook',
😞 I gettttt it but that's lame!

2016-12-16 04:20 UTC, t3ddftw commented on connector_easypost_tracker/models/stock_picking_tracking_event.py
> +        ('odoo_uniq', 'unique(backend_id, odoo_id)',
Nope, `backend_id` and `easypost_id` are the only unique constraint imposed there.

2016-12-16 04:21 UTC, t3ddftw commented on connector_easypost_tracker/models/stock_picking_tracking_location.py
> +    _sql_constraints = [
Negative, ghost rider. See my previous comment on the subject :)

2016-12-16 04:39 UTC, t3ddftw commented
My apologies @lasley, auto-pilot took over and I squashed most of my changes 😞 . To recap, I:

* Updated the route in the controller
* Added a missing trailing comma in the controller
* Added a missing trailing comma in models/stock_picking_tracking_event.py
* Moved `ObjectDict` class to its own file in unit/

2016-12-16 18:06 UTC, lasley approved these changes
Thanks @t3ddftw

2016-12-16 18:06 UTC, merged